; SFX indexes (see audio/sfx_pointers.asm)
	const_def
	const SFX_ITEM                        ; 00
	const SFX_LEVEL_UP                    ; 01
	const SFX_EVO_DITTY                   ; 02
	const SFX_GEN_1_DEX_REWARD            ; 03
	const SFX_TRADE_COMPLETE              ; 04
	const SFX_PL_LONG                     ; 05
	const SFX_CAUGHT_MON                  ; 06
	const SFX_KEY_ITEM                    ; 07
	const SFX_PL_SHORT                    ; 08
	const SFX_REGISTER_EMAIL              ; 09
	const SFX_3RD_PLACE                   ; 0a
	const SFX_GET_EGG                     ; 0b
	const SFX_GET_EGG_DUP                 ; 0c
	const SFX_MOVE_DELETED                ; 0d
	const SFX_2ND_PLACE                   ; 0e
	const SFX_1ST_PLACE                   ; 0f
	const SFX_CHOOSE_A_CARD               ; 10
	const SFX_GET_TM                      ; 11
	const SFX_GET_BADGE                   ; 12
	const SFX_QUIT_SLOTS                  ; 13
	const SFX_FAIL                        ; 14
	const SFX_KEEP_AT_IT                  ; 15
	const SFX_NOT_TOO_SHABBY              ; 16
	const SFX_ALMOST_FINISHED             ; 17
	const SFX_COMPLETED_DEX               ; 18
	const SFX_POKEBALLS_PLACED_ON_TABLE   ; 19
	const SFX_POTION                      ; 1a
	const SFX_FULL_HEAL                   ; 1b
	const SFX_MENU                        ; 1c
	const SFX_READ_TEXT                   ; 1d
	const SFX_READ_TEXT_2                 ; 1e
	const SFX_POISON                      ; 1f
	const SFX_GOT_SAFARI_BALLS            ; 20
	const SFX_BOOT_PC                     ; 21
	const SFX_SHUT_DOWN_PC                ; 22
	const SFX_CHOOSE_PC_OPTION            ; 23
	const SFX_ESCAPE_ROPE                 ; 24
	const SFX_PUSH_BUTTON                 ; 25
	const SFX_SECOND_PART_OF_ITEMFINDER   ; 26
	const SFX_WARP_TO                     ; 27
	const SFX_WARP_FROM                   ; 28
	const SFX_CHANGE_DEX_MODE             ; 29
	const SFX_JUMP_OVER_LEDGE             ; 2a
	const SFX_GRASS_RUSTLE                ; 2b
	const SFX_FLY                         ; 2c
	const SFX_WRONG                       ; 2d
	const SFX_SQUEAK                      ; 2e
	const SFX_STRENGTH                    ; 2f
	const SFX_BOAT                        ; 30
	const SFX_WALL_OPEN                   ; 31
	const SFX_PLACE_PUZZLE_PIECE_DOWN     ; 32
	const SFX_ENTER_DOOR                  ; 33
	const SFX_SWITCH_POKEMON              ; 34
	const SFX_TALLY                       ; 35
	const SFX_TRANSACTION                 ; 36
	const SFX_EXIT_BUILDING               ; 37
	const SFX_BUMP                        ; 38
	const SFX_SAVE                        ; 39
	const SFX_POKEFLUTE                   ; 3a
	const SFX_ELEVATOR_END                ; 3b
	const SFX_THROW_BALL                  ; 3c
	const SFX_BALL_POOF                   ; 3d
	const SFX_FAINT                       ; 3e
	const SFX_RUN                         ; 3f
	const SFX_DEX_UPDATE                  ; 40
	const SFX_PECK                        ; 41
	const SFX_KINESIS                     ; 42
	const SFX_LICK                        ; 43
	const SFX_POUND                       ; 44
	const SFX_MOVE_PUZZLE_PIECE           ; 45
	const SFX_COMET_PUNCH                 ; 46
	const SFX_MEGA_PUNCH                  ; 47
	const SFX_SCRATCH                     ; 48
	const SFX_VICEGRIP                    ; 49
	const SFX_RAZOR_WIND                  ; 4a
	const SFX_CUT                         ; 4b
	const SFX_WING_ATTACK                 ; 4c
	const SFX_WHIRLWIND                   ; 4d
	const SFX_BIND                        ; 4e
	const SFX_VINE_WHIP                   ; 4f
	const SFX_DOUBLE_KICK                 ; 50
	const SFX_MEGA_KICK                   ; 51
	const SFX_HEADBUTT                    ; 52
	const SFX_HORN_ATTACK                 ; 53
	const SFX_TACKLE                      ; 54
	const SFX_POISON_STING                ; 55
	const SFX_POWDER                      ; 56
	const SFX_DOUBLESLAP                  ; 57
	const SFX_BITE                        ; 58
	const SFX_JUMP_KICK                   ; 59
	const SFX_STOMP                       ; 5a
	const SFX_TAIL_WHIP                   ; 5b
	const SFX_KARATE_CHOP                 ; 5c
	const SFX_SUBMISSION                  ; 5d
	const SFX_WATER_GUN                   ; 5e
	const SFX_SWORDS_DANCE                ; 5f
	const SFX_THUNDER                     ; 60
	const SFX_SUPERSONIC                  ; 61
	const SFX_LEER                        ; 62
	const SFX_EMBER                       ; 63
	const SFX_BUBBLEBEAM                  ; 64
	const SFX_HYDRO_PUMP                  ; 65
	const SFX_SURF                        ; 66
	const SFX_PSYBEAM                     ; 67
	const SFX_CHARGE                      ; 68
	const SFX_THUNDERSHOCK                ; 69
	const SFX_PSYCHIC                     ; 6a
	const SFX_SCREECH                     ; 6b
	const SFX_BONE_CLUB                   ; 6c
	const SFX_SHARPEN                     ; 6d
	const SFX_EGG_BOMB                    ; 6e
	const SFX_SING                        ; 6f
	const SFX_HYPER_BEAM                  ; 70
	const SFX_SHINE                       ; 71
	const SFX_UNKNOWN_72                  ; 72
	const SFX_RB_DEMO_LUNGE               ; 73
	const SFX_UNKNOWN_74                  ; 74
	const SFX_SWITCH_POCKETS              ; 75
	const SFX_RB_VERSION_NAME_ENTRANCE    ; 76
	const SFX_BURN                        ; 77
	const SFX_TITLE_SCREEN_ENTRANCE       ; 78
	const SFX_RBY_SLOT_STOP               ; 79
	const SFX_GET_COIN_FROM_SLOTS         ; 7a
	const SFX_SLOT_MACHINE_START          ; 7b
	const SFX_METRONOME                   ; 7c
	const SFX_CALL                        ; 7d
	const SFX_HANG_UP                     ; 7e
	const SFX_NO_SIGNAL                   ; 7f
	const SFX_SANDSTORM                   ; 80
	const SFX_ELEVATOR                    ; 81
	const SFX_PROTECT                     ; 82
	const SFX_SKETCH                      ; 83
	const SFX_RAIN_DANCE                  ; 84
	const SFX_AEROBLAST                   ; 85
	const SFX_SPARK                       ; 86
	const SFX_CURSE                       ; 87
	const SFX_RAGE                        ; 88
	const SFX_THIEF                       ; 89
	const SFX_THIEF_2                     ; 8a
	const SFX_SPIDER_WEB                  ; 8b
	const SFX_MIND_READER                 ; 8c
	const SFX_NIGHTMARE                   ; 8d
	const SFX_SNORE                       ; 8e
	const SFX_SWEET_KISS                  ; 8f
	const SFX_SWEET_KISS_2                ; 90
	const SFX_BELLY_DRUM                  ; 91
	const SFX_TOXIC                       ; 92
	const SFX_SLUDGE_BOMB                 ; 93
	const SFX_FORESIGHT                   ; 94
	const SFX_SPITE                       ; 95
	const SFX_OUTRAGE                     ; 96
	const SFX_PERISH_SONG                 ; 97
	const SFX_GIGA_DRAIN                  ; 98
	const SFX_ATTRACT                     ; 99
	const SFX_KINESIS_2                   ; 9a
	const SFX_ZAP_CANNON                  ; 9b
	const SFX_MEAN_LOOK                   ; 9c
	const SFX_HEAL_BELL                   ; 9d
	const SFX_RETURN                      ; 9e
	const SFX_EXP_BAR                     ; 9f
	const SFX_MILK_DRINK                  ; a0
	const SFX_PRESENT                     ; a1
	const SFX_MORNING_SUN                 ; a2
	const SFX_EGG_CRACK                   ; a3
	const SFX_EVOLVED                     ; a4
	const SFX_MASTER_BALL                 ; a5
	const SFX_EGG_HATCH                   ; a6
	const SFX_GS_INTRO_CHARIZARD_FIREBALL ; a7
	const SFX_GS_INTRO_POKEMON_APPEARS    ; a8
	const SFX_FLASH                       ; a9
	const SFX_GAME_FREAK_LOGO_GS          ; aa
	const SFX_NOT_VERY_EFFECTIVE          ; ab
	const SFX_DAMAGE                      ; ac
	const SFX_SUPER_EFFECTIVE             ; ad
	const SFX_BALL_BOUNCE                 ; ae
	const SFX_MOONLIGHT                   ; af
	const SFX_ENCORE                      ; b0
	const SFX_BEAT_UP                     ; b1
	const SFX_BATON_PASS                  ; b2
	const SFX_BALL_WOBBLE                 ; b3
	const SFX_SWEET_SCENT                 ; b4
	const SFX_SWEET_SCENT_2               ; b5
	const SFX_HIT_END_OF_EXP_BAR          ; b6
	const SFX_GIVE_TRADEMON               ; b7
	const SFX_GET_TRADEMON                ; b8
	const SFX_TRAIN_ARRIVED               ; b9
	const SFX_STOP_SLOT                   ; ba
	const SFX_2_BOOPS                     ; bb
; crystal
	const SFX_GLASS_TING                  ; bc
	const SFX_GLASS_TING_2                ; bd
	const SFX_INTRO_UNOWN_1               ; be
	const SFX_INTRO_UNOWN_2               ; bf
	const SFX_INTRO_UNOWN_3               ; c0
	const SFX_DITTO_POP_UP                ; c1
	const SFX_DITTO_TRANSFORM             ; c2
	const SFX_INTRO_SUICUNE_1             ; c3
	const SFX_INTRO_PICHU                 ; c4
	const SFX_INTRO_SUICUNE_2             ; c5
	const SFX_INTRO_SUICUNE_3             ; c6
	const SFX_DITTO_BOUNCE                ; c7
	const SFX_INTRO_SUICUNE_4             ; c8
	const SFX_GAME_FREAK_PRESENTS         ; c9
	const SFX_TINGLE                      ; ca
	const SFX_INTRO_WHOOSH                ; cb
	const SFX_TWO_PC_BEEPS                ; cc
	const SFX_4_NOTE_DITTY                ; cd
	const SFX_TWINKLE                     ; ce
; imported
	const SFX_SHOOTING_STAR               ; cf
	const SFX_RBY_SING                    ; d0
; placeholder
	const SFX_LOCK_ON                     ; d1
	const SFX_FLAIL                       ; d2
	const SFX_BALL_CLOSE                  ; d3
	const SFX_IN_LOVE                     ; d4
	const SFX_AMNESIA                     ; d5
	const SFX_EXP_BAR_FULL                ; d6
	const SFX_MIMIC_D7                    ; d7
	const SFX_MIMIC_D8                    ; d8
	const SFX_MIMIC_D9                    ; d9
	const SFX_MIMIC_DA                    ; da
	const SFX_MIMIC_DB                    ; db
	const SFX_MIMIC_DC                    ; dc
	const SFX_MIMIC_DD                    ; dd
	const SFX_BALL_SHAKE                  ; de
	const SFX_EGG_ROLL                    ; df
	const SFX_SMOKESCREEN                 ; e0
	const SFX_SPIKES_E1                   ; e1
	const SFX_SPIKES_E2                   ; e2
	const SFX_RECOVER                     ; e3
	const SFX_PAY_DAY                     ; e4