Cries:
; gen 1
	dba Cry_Hare1
	dba Cry_Hare2
	dba Cry_Slowpoke
	dba Cry_Kangaskhan
	dba Cry_Rhyhorn
	dba Cry_Grimer
	dba Cry_Voltorb
	dba Cry_Gengar
	dba Cry_IvysaurOld
	dba Cry_Nidoking
	dba Cry_Nidoqueen
	dba Cry_Exeggcute
	dba Cry_Lickitung
	dba Cry_Exeggcutor
	dba Cry_Pip
	dba Cry_Gyaoon
	dba Cry_Omom
	dba Cry_Rhydon
	dba Cry_Tangela
	dba Cry_Omega
	dba Cry_Pinsir
	dba Cry_Wing
	dba Cry_Scyther
	dba Cry_Gyarados
	dba Cry_Shellder
	dba Cry_Cubone
	dba Cry_Ambler
	dba Cry_Lapras
	dba Cry_Gastly
	dba Cry_Karabatheo
	dba Cry_Staryu
	dba Cry_Slowbro
	dba Cry_34
	dba Cry_36
	dba Cry_Rattata
	dba Cry_Kingsaurus
	dba Cry_Stegon
	dba Cry_Eleking
; gen 2
	dba Cry_Crow
	dba Cry_Derble4
	dba Cry_Derble1
	dba Cry_Feline
	dba Cry_Tyranitar
	dba Cry_Bleet1
	dba Cry_Derble2
	dba Cry_Hoothoot
	dba Cry_Phanpy
	dba Cry_Slowking
	dba Cry_Growl
	dba Cry_Chikorita
	dba Cry_Roar60
	dba Cry_Miltank
	dba Cry_CottonCat
	dba Cry_Hitmontop
	dba Cry_Ledyba
	dba Cry_Tiger
	dba Cry_Sneasel
	dba Cry_Mantine
	dba Cry_Roar10
	dba Cry_Roar20
	dba Cry_Roar30
	dba Cry_Roar40
	dba Cry_Roar50
	dba Cry_Suicune
	dba Cry_Mouse
	dba Cry_Ho_oh
	dba Cry_Granbull
	dba Cry_Donphan

; new pointers
	dba Cry_Earthtron
	dba Cry_H45
	dba Cry_H46
