
	const_def
; gear flags
	const ENGINE_MAP_CARD
	const ENGINE_RADIO_CARD
	const ENGINE_EMAIL_CARD
	const ENGINE_EXPN_CARD
	const ENGINE_POKEGEAR
; stat flags
	const ENGINE_POKEDEX
	const ENGINE_CAUGHT_POKERUS
	const ENGINE_CREDITS_SKIP
; fly points
	const ENGINE_FLYPOINT_PLAYERS_HOUSE
	const ENGINE_FLYPOINT_DEBUG
	const ENGINE_FLYPOINT_COTTAGE
; badges
	const ENGINE_GADGETBADGE
	const ENGINE_IVYBADGE
	const ENGINE_VENOMBADGE
	const ENGINE_VIDEOBADGE
	const ENGINE_RODEOBADGE
	const ENGINE_BONBADGE
	const ENGINE_DASHBADGE
	const ENGINE_SCENERYBADGE
; misc
	const ENGINE_SWARM
	const ENGINE_BIKE_SHOP_CALL_ENABLED
NUM_ENGINE_FLAGS EQU const_value